'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
'
Namespace SCTServer
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SCTServerSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SCTServer
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private cslaCredentialsValueField As CslaCredentials
        
        Private OpenConnectionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CloseConnectionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private KeepConnectionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAdvertisingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetSystemConfigurationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AdDisplayOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AdClickThruOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SubscriberCountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConnectedSubscriberCountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DisConnectedSubscriberCountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsConnectedSubscriberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddSubsciberAccountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EditSubsciberAccountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSubscriberAccountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UninstallClientProgramOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ChangeSubscriberWebPasswordOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ChangeSubscriberComputerPasswordOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSubscriberStolenReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddSubsciberStolenReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EditSubsciberStolenReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SCT.Web.DataFlow.My.MySettings.Default.SCT_Web_DataFlow_SCTServer_SCTServer
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property CslaCredentialsValue() As CslaCredentials
            Get
                Return Me.cslaCredentialsValueField
            End Get
            Set
                Me.cslaCredentialsValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event OpenConnectionCompleted As OpenConnectionCompletedEventHandler
        
        '''<remarks/>
        Public Event CloseConnectionCompleted As CloseConnectionCompletedEventHandler
        
        '''<remarks/>
        Public Event KeepConnectionCompleted As KeepConnectionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAdvertisingCompleted As GetAdvertisingCompletedEventHandler
        
        '''<remarks/>
        Public Event SetSystemConfigurationCompleted As SetSystemConfigurationCompletedEventHandler
        
        '''<remarks/>
        Public Event AdDisplayCompleted As AdDisplayCompletedEventHandler
        
        '''<remarks/>
        Public Event AdClickThruCompleted As AdClickThruCompletedEventHandler
        
        '''<remarks/>
        Public Event SubscriberCountCompleted As SubscriberCountCompletedEventHandler
        
        '''<remarks/>
        Public Event ConnectedSubscriberCountCompleted As ConnectedSubscriberCountCompletedEventHandler
        
        '''<remarks/>
        Public Event DisConnectedSubscriberCountCompleted As DisConnectedSubscriberCountCompletedEventHandler
        
        '''<remarks/>
        Public Event IsConnectedSubscriberCompleted As IsConnectedSubscriberCompletedEventHandler
        
        '''<remarks/>
        Public Event AddSubsciberAccountCompleted As AddSubsciberAccountCompletedEventHandler
        
        '''<remarks/>
        Public Event EditSubsciberAccountCompleted As EditSubsciberAccountCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSubscriberAccountCompleted As GetSubscriberAccountCompletedEventHandler
        
        '''<remarks/>
        Public Event UninstallClientProgramCompleted As UninstallClientProgramCompletedEventHandler
        
        '''<remarks/>
        Public Event ChangeSubscriberWebPasswordCompleted As ChangeSubscriberWebPasswordCompletedEventHandler
        
        '''<remarks/>
        Public Event ChangeSubscriberComputerPasswordCompleted As ChangeSubscriberComputerPasswordCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSubscriberStolenReportCompleted As GetSubscriberStolenReportCompletedEventHandler
        
        '''<remarks/>
        Public Event AddSubsciberStolenReportCompleted As AddSubsciberStolenReportCompletedEventHandler
        
        '''<remarks/>
        Public Event EditSubsciberStolenReportCompleted As EditSubsciberStolenReportCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OpenConnection", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OpenConnection(ByVal connectionRequest As ClsConnectionRequest) As ClsConnectionResponse
            Dim results() As Object = Me.Invoke("OpenConnection", New Object() {connectionRequest})
            Return CType(results(0),ClsConnectionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OpenConnectionAsync(ByVal connectionRequest As ClsConnectionRequest)
            Me.OpenConnectionAsync(connectionRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OpenConnectionAsync(ByVal connectionRequest As ClsConnectionRequest, ByVal userState As Object)
            If (Me.OpenConnectionOperationCompleted Is Nothing) Then
                Me.OpenConnectionOperationCompleted = AddressOf Me.OnOpenConnectionOperationCompleted
            End If
            Me.InvokeAsync("OpenConnection", New Object() {connectionRequest}, Me.OpenConnectionOperationCompleted, userState)
        End Sub
        
        Private Sub OnOpenConnectionOperationCompleted(ByVal arg As Object)
            If (Not (Me.OpenConnectionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OpenConnectionCompleted(Me, New OpenConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CloseConnection", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CloseConnection()
            Me.Invoke("CloseConnection", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CloseConnectionAsync()
            Me.CloseConnectionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CloseConnectionAsync(ByVal userState As Object)
            If (Me.CloseConnectionOperationCompleted Is Nothing) Then
                Me.CloseConnectionOperationCompleted = AddressOf Me.OnCloseConnectionOperationCompleted
            End If
            Me.InvokeAsync("CloseConnection", New Object(-1) {}, Me.CloseConnectionOperationCompleted, userState)
        End Sub
        
        Private Sub OnCloseConnectionOperationCompleted(ByVal arg As Object)
            If (Not (Me.CloseConnectionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CloseConnectionCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KeepConnection", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function KeepConnection(ByVal hostIPInfo As ClsHostIPInfo) As ClsConnectionResponse
            Dim results() As Object = Me.Invoke("KeepConnection", New Object() {hostIPInfo})
            Return CType(results(0),ClsConnectionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub KeepConnectionAsync(ByVal hostIPInfo As ClsHostIPInfo)
            Me.KeepConnectionAsync(hostIPInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub KeepConnectionAsync(ByVal hostIPInfo As ClsHostIPInfo, ByVal userState As Object)
            If (Me.KeepConnectionOperationCompleted Is Nothing) Then
                Me.KeepConnectionOperationCompleted = AddressOf Me.OnKeepConnectionOperationCompleted
            End If
            Me.InvokeAsync("KeepConnection", New Object() {hostIPInfo}, Me.KeepConnectionOperationCompleted, userState)
        End Sub
        
        Private Sub OnKeepConnectionOperationCompleted(ByVal arg As Object)
            If (Not (Me.KeepConnectionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent KeepConnectionCompleted(Me, New KeepConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAdvertising", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAdvertising(ByVal subscriberTime As Date) As ClsAdvertisingInfo
            Dim results() As Object = Me.Invoke("GetAdvertising", New Object() {subscriberTime})
            Return CType(results(0),ClsAdvertisingInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAdvertisingAsync(ByVal subscriberTime As Date)
            Me.GetAdvertisingAsync(subscriberTime, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAdvertisingAsync(ByVal subscriberTime As Date, ByVal userState As Object)
            If (Me.GetAdvertisingOperationCompleted Is Nothing) Then
                Me.GetAdvertisingOperationCompleted = AddressOf Me.OnGetAdvertisingOperationCompleted
            End If
            Me.InvokeAsync("GetAdvertising", New Object() {subscriberTime}, Me.GetAdvertisingOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAdvertisingOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAdvertisingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAdvertisingCompleted(Me, New GetAdvertisingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetSystemConfiguration", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SetSystemConfiguration(ByVal systemConfigurationInfo As ClsComputerConfigurationInfo)
            Me.Invoke("SetSystemConfiguration", New Object() {systemConfigurationInfo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetSystemConfigurationAsync(ByVal systemConfigurationInfo As ClsComputerConfigurationInfo)
            Me.SetSystemConfigurationAsync(systemConfigurationInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetSystemConfigurationAsync(ByVal systemConfigurationInfo As ClsComputerConfigurationInfo, ByVal userState As Object)
            If (Me.SetSystemConfigurationOperationCompleted Is Nothing) Then
                Me.SetSystemConfigurationOperationCompleted = AddressOf Me.OnSetSystemConfigurationOperationCompleted
            End If
            Me.InvokeAsync("SetSystemConfiguration", New Object() {systemConfigurationInfo}, Me.SetSystemConfigurationOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetSystemConfigurationOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetSystemConfigurationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetSystemConfigurationCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdDisplay", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AdDisplay(ByVal AdHistoryInfo As ClsAdvertisingInfo)
            Me.Invoke("AdDisplay", New Object() {AdHistoryInfo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AdDisplayAsync(ByVal AdHistoryInfo As ClsAdvertisingInfo)
            Me.AdDisplayAsync(AdHistoryInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AdDisplayAsync(ByVal AdHistoryInfo As ClsAdvertisingInfo, ByVal userState As Object)
            If (Me.AdDisplayOperationCompleted Is Nothing) Then
                Me.AdDisplayOperationCompleted = AddressOf Me.OnAdDisplayOperationCompleted
            End If
            Me.InvokeAsync("AdDisplay", New Object() {AdHistoryInfo}, Me.AdDisplayOperationCompleted, userState)
        End Sub
        
        Private Sub OnAdDisplayOperationCompleted(ByVal arg As Object)
            If (Not (Me.AdDisplayCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AdDisplayCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdClickThru", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AdClickThru(ByVal AdHistoryInfo As ClsAdvertisingInfo)
            Me.Invoke("AdClickThru", New Object() {AdHistoryInfo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AdClickThruAsync(ByVal AdHistoryInfo As ClsAdvertisingInfo)
            Me.AdClickThruAsync(AdHistoryInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AdClickThruAsync(ByVal AdHistoryInfo As ClsAdvertisingInfo, ByVal userState As Object)
            If (Me.AdClickThruOperationCompleted Is Nothing) Then
                Me.AdClickThruOperationCompleted = AddressOf Me.OnAdClickThruOperationCompleted
            End If
            Me.InvokeAsync("AdClickThru", New Object() {AdHistoryInfo}, Me.AdClickThruOperationCompleted, userState)
        End Sub
        
        Private Sub OnAdClickThruOperationCompleted(ByVal arg As Object)
            If (Not (Me.AdClickThruCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AdClickThruCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubscriberCount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SubscriberCount() As Long
            Dim results() As Object = Me.Invoke("SubscriberCount", New Object(-1) {})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SubscriberCountAsync()
            Me.SubscriberCountAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SubscriberCountAsync(ByVal userState As Object)
            If (Me.SubscriberCountOperationCompleted Is Nothing) Then
                Me.SubscriberCountOperationCompleted = AddressOf Me.OnSubscriberCountOperationCompleted
            End If
            Me.InvokeAsync("SubscriberCount", New Object(-1) {}, Me.SubscriberCountOperationCompleted, userState)
        End Sub
        
        Private Sub OnSubscriberCountOperationCompleted(ByVal arg As Object)
            If (Not (Me.SubscriberCountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SubscriberCountCompleted(Me, New SubscriberCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConnectedSubscriberCount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConnectedSubscriberCount() As Long
            Dim results() As Object = Me.Invoke("ConnectedSubscriberCount", New Object(-1) {})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConnectedSubscriberCountAsync()
            Me.ConnectedSubscriberCountAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConnectedSubscriberCountAsync(ByVal userState As Object)
            If (Me.ConnectedSubscriberCountOperationCompleted Is Nothing) Then
                Me.ConnectedSubscriberCountOperationCompleted = AddressOf Me.OnConnectedSubscriberCountOperationCompleted
            End If
            Me.InvokeAsync("ConnectedSubscriberCount", New Object(-1) {}, Me.ConnectedSubscriberCountOperationCompleted, userState)
        End Sub
        
        Private Sub OnConnectedSubscriberCountOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConnectedSubscriberCountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConnectedSubscriberCountCompleted(Me, New ConnectedSubscriberCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisConnectedSubscriberCount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DisConnectedSubscriberCount() As Long
            Dim results() As Object = Me.Invoke("DisConnectedSubscriberCount", New Object(-1) {})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DisConnectedSubscriberCountAsync()
            Me.DisConnectedSubscriberCountAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DisConnectedSubscriberCountAsync(ByVal userState As Object)
            If (Me.DisConnectedSubscriberCountOperationCompleted Is Nothing) Then
                Me.DisConnectedSubscriberCountOperationCompleted = AddressOf Me.OnDisConnectedSubscriberCountOperationCompleted
            End If
            Me.InvokeAsync("DisConnectedSubscriberCount", New Object(-1) {}, Me.DisConnectedSubscriberCountOperationCompleted, userState)
        End Sub
        
        Private Sub OnDisConnectedSubscriberCountOperationCompleted(ByVal arg As Object)
            If (Not (Me.DisConnectedSubscriberCountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DisConnectedSubscriberCountCompleted(Me, New DisConnectedSubscriberCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsConnectedSubscriber", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsConnectedSubscriber(ByVal SubscriberID As Long) As Boolean
            Dim results() As Object = Me.Invoke("IsConnectedSubscriber", New Object() {SubscriberID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsConnectedSubscriberAsync(ByVal SubscriberID As Long)
            Me.IsConnectedSubscriberAsync(SubscriberID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsConnectedSubscriberAsync(ByVal SubscriberID As Long, ByVal userState As Object)
            If (Me.IsConnectedSubscriberOperationCompleted Is Nothing) Then
                Me.IsConnectedSubscriberOperationCompleted = AddressOf Me.OnIsConnectedSubscriberOperationCompleted
            End If
            Me.InvokeAsync("IsConnectedSubscriber", New Object() {SubscriberID}, Me.IsConnectedSubscriberOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsConnectedSubscriberOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsConnectedSubscriberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsConnectedSubscriberCompleted(Me, New IsConnectedSubscriberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddSubsciberAccount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AddSubsciberAccount(ByVal AccountData As ClsSubscriberAccountData)
            Me.Invoke("AddSubsciberAccount", New Object() {AccountData})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddSubsciberAccountAsync(ByVal AccountData As ClsSubscriberAccountData)
            Me.AddSubsciberAccountAsync(AccountData, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddSubsciberAccountAsync(ByVal AccountData As ClsSubscriberAccountData, ByVal userState As Object)
            If (Me.AddSubsciberAccountOperationCompleted Is Nothing) Then
                Me.AddSubsciberAccountOperationCompleted = AddressOf Me.OnAddSubsciberAccountOperationCompleted
            End If
            Me.InvokeAsync("AddSubsciberAccount", New Object() {AccountData}, Me.AddSubsciberAccountOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddSubsciberAccountOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddSubsciberAccountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddSubsciberAccountCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditSubsciberAccount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub EditSubsciberAccount(ByVal AccountData As ClsSubscriberAccountData)
            Me.Invoke("EditSubsciberAccount", New Object() {AccountData})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EditSubsciberAccountAsync(ByVal AccountData As ClsSubscriberAccountData)
            Me.EditSubsciberAccountAsync(AccountData, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EditSubsciberAccountAsync(ByVal AccountData As ClsSubscriberAccountData, ByVal userState As Object)
            If (Me.EditSubsciberAccountOperationCompleted Is Nothing) Then
                Me.EditSubsciberAccountOperationCompleted = AddressOf Me.OnEditSubsciberAccountOperationCompleted
            End If
            Me.InvokeAsync("EditSubsciberAccount", New Object() {AccountData}, Me.EditSubsciberAccountOperationCompleted, userState)
        End Sub
        
        Private Sub OnEditSubsciberAccountOperationCompleted(ByVal arg As Object)
            If (Not (Me.EditSubsciberAccountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EditSubsciberAccountCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubscriberAccount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSubscriberAccount(ByVal SubscriberID As Long) As ClsSubscriberAccountData
            Dim results() As Object = Me.Invoke("GetSubscriberAccount", New Object() {SubscriberID})
            Return CType(results(0),ClsSubscriberAccountData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSubscriberAccountAsync(ByVal SubscriberID As Long)
            Me.GetSubscriberAccountAsync(SubscriberID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSubscriberAccountAsync(ByVal SubscriberID As Long, ByVal userState As Object)
            If (Me.GetSubscriberAccountOperationCompleted Is Nothing) Then
                Me.GetSubscriberAccountOperationCompleted = AddressOf Me.OnGetSubscriberAccountOperationCompleted
            End If
            Me.InvokeAsync("GetSubscriberAccount", New Object() {SubscriberID}, Me.GetSubscriberAccountOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSubscriberAccountOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSubscriberAccountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSubscriberAccountCompleted(Me, New GetSubscriberAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UninstallClientProgram", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UninstallClientProgram(ByVal SubscriberID As Long)
            Me.Invoke("UninstallClientProgram", New Object() {SubscriberID})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UninstallClientProgramAsync(ByVal SubscriberID As Long)
            Me.UninstallClientProgramAsync(SubscriberID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UninstallClientProgramAsync(ByVal SubscriberID As Long, ByVal userState As Object)
            If (Me.UninstallClientProgramOperationCompleted Is Nothing) Then
                Me.UninstallClientProgramOperationCompleted = AddressOf Me.OnUninstallClientProgramOperationCompleted
            End If
            Me.InvokeAsync("UninstallClientProgram", New Object() {SubscriberID}, Me.UninstallClientProgramOperationCompleted, userState)
        End Sub
        
        Private Sub OnUninstallClientProgramOperationCompleted(ByVal arg As Object)
            If (Not (Me.UninstallClientProgramCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UninstallClientProgramCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeSubscriberWebPassword", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub ChangeSubscriberWebPassword(ByVal SubscriberID As Long, ByVal newPassword As String)
            Me.Invoke("ChangeSubscriberWebPassword", New Object() {SubscriberID, newPassword})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChangeSubscriberWebPasswordAsync(ByVal SubscriberID As Long, ByVal newPassword As String)
            Me.ChangeSubscriberWebPasswordAsync(SubscriberID, newPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChangeSubscriberWebPasswordAsync(ByVal SubscriberID As Long, ByVal newPassword As String, ByVal userState As Object)
            If (Me.ChangeSubscriberWebPasswordOperationCompleted Is Nothing) Then
                Me.ChangeSubscriberWebPasswordOperationCompleted = AddressOf Me.OnChangeSubscriberWebPasswordOperationCompleted
            End If
            Me.InvokeAsync("ChangeSubscriberWebPassword", New Object() {SubscriberID, newPassword}, Me.ChangeSubscriberWebPasswordOperationCompleted, userState)
        End Sub
        
        Private Sub OnChangeSubscriberWebPasswordOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChangeSubscriberWebPasswordCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChangeSubscriberWebPasswordCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeSubscriberComputerPassword", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub ChangeSubscriberComputerPassword(ByVal SubscriberID As Long, ByVal newPassword As String)
            Me.Invoke("ChangeSubscriberComputerPassword", New Object() {SubscriberID, newPassword})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChangeSubscriberComputerPasswordAsync(ByVal SubscriberID As Long, ByVal newPassword As String)
            Me.ChangeSubscriberComputerPasswordAsync(SubscriberID, newPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChangeSubscriberComputerPasswordAsync(ByVal SubscriberID As Long, ByVal newPassword As String, ByVal userState As Object)
            If (Me.ChangeSubscriberComputerPasswordOperationCompleted Is Nothing) Then
                Me.ChangeSubscriberComputerPasswordOperationCompleted = AddressOf Me.OnChangeSubscriberComputerPasswordOperationCompleted
            End If
            Me.InvokeAsync("ChangeSubscriberComputerPassword", New Object() {SubscriberID, newPassword}, Me.ChangeSubscriberComputerPasswordOperationCompleted, userState)
        End Sub
        
        Private Sub OnChangeSubscriberComputerPasswordOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChangeSubscriberComputerPasswordCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChangeSubscriberComputerPasswordCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubscriberStolenReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSubscriberStolenReport(ByVal SubscriberID As Long) As ClsSubscriberStolenReportData
            Dim results() As Object = Me.Invoke("GetSubscriberStolenReport", New Object() {SubscriberID})
            Return CType(results(0),ClsSubscriberStolenReportData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSubscriberStolenReportAsync(ByVal SubscriberID As Long)
            Me.GetSubscriberStolenReportAsync(SubscriberID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSubscriberStolenReportAsync(ByVal SubscriberID As Long, ByVal userState As Object)
            If (Me.GetSubscriberStolenReportOperationCompleted Is Nothing) Then
                Me.GetSubscriberStolenReportOperationCompleted = AddressOf Me.OnGetSubscriberStolenReportOperationCompleted
            End If
            Me.InvokeAsync("GetSubscriberStolenReport", New Object() {SubscriberID}, Me.GetSubscriberStolenReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSubscriberStolenReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSubscriberStolenReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSubscriberStolenReportCompleted(Me, New GetSubscriberStolenReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddSubsciberStolenReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AddSubsciberStolenReport(ByVal SubscriberID As Long, ByVal stolenReportData As ClsSubscriberStolenReportData)
            Me.Invoke("AddSubsciberStolenReport", New Object() {SubscriberID, stolenReportData})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddSubsciberStolenReportAsync(ByVal SubscriberID As Long, ByVal stolenReportData As ClsSubscriberStolenReportData)
            Me.AddSubsciberStolenReportAsync(SubscriberID, stolenReportData, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddSubsciberStolenReportAsync(ByVal SubscriberID As Long, ByVal stolenReportData As ClsSubscriberStolenReportData, ByVal userState As Object)
            If (Me.AddSubsciberStolenReportOperationCompleted Is Nothing) Then
                Me.AddSubsciberStolenReportOperationCompleted = AddressOf Me.OnAddSubsciberStolenReportOperationCompleted
            End If
            Me.InvokeAsync("AddSubsciberStolenReport", New Object() {SubscriberID, stolenReportData}, Me.AddSubsciberStolenReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddSubsciberStolenReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddSubsciberStolenReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddSubsciberStolenReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CslaCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditSubsciberStolenReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub EditSubsciberStolenReport(ByVal SubscriberID As Long, ByVal stolenReportData As ClsSubscriberStolenReportData)
            Me.Invoke("EditSubsciberStolenReport", New Object() {SubscriberID, stolenReportData})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EditSubsciberStolenReportAsync(ByVal SubscriberID As Long, ByVal stolenReportData As ClsSubscriberStolenReportData)
            Me.EditSubsciberStolenReportAsync(SubscriberID, stolenReportData, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EditSubsciberStolenReportAsync(ByVal SubscriberID As Long, ByVal stolenReportData As ClsSubscriberStolenReportData, ByVal userState As Object)
            If (Me.EditSubsciberStolenReportOperationCompleted Is Nothing) Then
                Me.EditSubsciberStolenReportOperationCompleted = AddressOf Me.OnEditSubsciberStolenReportOperationCompleted
            End If
            Me.InvokeAsync("EditSubsciberStolenReport", New Object() {SubscriberID, stolenReportData}, Me.EditSubsciberStolenReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnEditSubsciberStolenReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.EditSubsciberStolenReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EditSubsciberStolenReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/", IsNullable:=false)>  _
    Partial Public Class CslaCredentials
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private computerSerialNumberField As String
        
        Private clientPasswordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property ComputerSerialNumber() As String
            Get
                Return Me.computerSerialNumberField
            End Get
            Set
                Me.computerSerialNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientPassword() As String
            Get
                Return Me.clientPasswordField
            End Get
            Set
                Me.clientPasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsSubscriberDemographicData
        
        Private idField As Long
        
        Private tagField As String
        
        Private answerField As String
        
        '''<remarks/>
        Public Property ID() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tag() As String
            Get
                Return Me.tagField
            End Get
            Set
                Me.tagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Answer() As String
            Get
                Return Me.answerField
            End Get
            Set
                Me.answerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsSubscriberStolenReportData
        
        Private idField As Long
        
        Private dateReportMissingField As Date
        
        Private lastKnownLocationDescriptionField As String
        
        Private dateReportFoundField As Date
        
        Private activeForAlertsField As Boolean
        
        Private actionToTakeField As Integer
        
        '''<remarks/>
        Public Property ID() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateReportMissing() As Date
            Get
                Return Me.dateReportMissingField
            End Get
            Set
                Me.dateReportMissingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastKnownLocationDescription() As String
            Get
                Return Me.lastKnownLocationDescriptionField
            End Get
            Set
                Me.lastKnownLocationDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateReportFound() As Date
            Get
                Return Me.dateReportFoundField
            End Get
            Set
                Me.dateReportFoundField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActiveForAlerts() As Boolean
            Get
                Return Me.activeForAlertsField
            End Get
            Set
                Me.activeForAlertsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActionToTake() As Integer
            Get
                Return Me.actionToTakeField
            End Get
            Set
                Me.actionToTakeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsSubscriberConnectionHistoryData
        
        Private idField As Long
        
        Private hostIPField As String
        
        Private hostLocalIPField As String
        
        Private connectionDateField As Date
        
        Private connectionTimeField As Date
        
        Private dNSResolutionIPField As String
        
        Private iPStateField As String
        
        Private iPCityField As String
        
        Private activityStatusField As String
        
        '''<remarks/>
        Public Property ID() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HostIP() As String
            Get
                Return Me.hostIPField
            End Get
            Set
                Me.hostIPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HostLocalIP() As String
            Get
                Return Me.hostLocalIPField
            End Get
            Set
                Me.hostLocalIPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConnectionDate() As Date
            Get
                Return Me.connectionDateField
            End Get
            Set
                Me.connectionDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConnectionTime() As Date
            Get
                Return Me.connectionTimeField
            End Get
            Set
                Me.connectionTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DNSResolutionIP() As String
            Get
                Return Me.dNSResolutionIPField
            End Get
            Set
                Me.dNSResolutionIPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IPState() As String
            Get
                Return Me.iPStateField
            End Get
            Set
                Me.iPStateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IPCity() As String
            Get
                Return Me.iPCityField
            End Get
            Set
                Me.iPCityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActivityStatus() As String
            Get
                Return Me.activityStatusField
            End Get
            Set
                Me.activityStatusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsSubscriberAccountData
        
        Private idField As Long
        
        Private connectedField As Boolean
        
        Private installClientProgramField As Boolean
        
        Private configurationHasChangedField As Boolean
        
        Private loginField As String
        
        Private computerSerialNumberField As String
        
        Private webPasswordField As String
        
        Private clientPasswordField As String
        
        Private hintByPassOneField As String
        
        Private hintByPassTwoField As String
        
        Private contactEmailField As String
        
        Private connectionHistoryField As ClsSubscriberConnectionHistoryData
        
        Private stolenReportField As ClsSubscriberStolenReportData
        
        Private demographicsField() As ClsSubscriberDemographicData
        
        '''<remarks/>
        Public Property ID() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connected() As Boolean
            Get
                Return Me.connectedField
            End Get
            Set
                Me.connectedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InstallClientProgram() As Boolean
            Get
                Return Me.installClientProgramField
            End Get
            Set
                Me.installClientProgramField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConfigurationHasChanged() As Boolean
            Get
                Return Me.configurationHasChangedField
            End Get
            Set
                Me.configurationHasChangedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Login() As String
            Get
                Return Me.loginField
            End Get
            Set
                Me.loginField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ComputerSerialNumber() As String
            Get
                Return Me.computerSerialNumberField
            End Get
            Set
                Me.computerSerialNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WebPassword() As String
            Get
                Return Me.webPasswordField
            End Get
            Set
                Me.webPasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientPassword() As String
            Get
                Return Me.clientPasswordField
            End Get
            Set
                Me.clientPasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HintByPassOne() As String
            Get
                Return Me.hintByPassOneField
            End Get
            Set
                Me.hintByPassOneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HintByPassTwo() As String
            Get
                Return Me.hintByPassTwoField
            End Get
            Set
                Me.hintByPassTwoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactEmail() As String
            Get
                Return Me.contactEmailField
            End Get
            Set
                Me.contactEmailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConnectionHistory() As ClsSubscriberConnectionHistoryData
            Get
                Return Me.connectionHistoryField
            End Get
            Set
                Me.connectionHistoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StolenReport() As ClsSubscriberStolenReportData
            Get
                Return Me.stolenReportField
            End Get
            Set
                Me.stolenReportField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Demographics() As ClsSubscriberDemographicData()
            Get
                Return Me.demographicsField
            End Get
            Set
                Me.demographicsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsAdvertisingInfo
        
        Private adHistoryIDField As Long
        
        Private aDUrlField As String
        
        Private aDHeightField As Integer
        
        Private aDWidthField As Integer
        
        '''<remarks/>
        Public Property AdHistoryID() As Long
            Get
                Return Me.adHistoryIDField
            End Get
            Set
                Me.adHistoryIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ADUrl() As String
            Get
                Return Me.aDUrlField
            End Get
            Set
                Me.aDUrlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ADHeight() As Integer
            Get
                Return Me.aDHeightField
            End Get
            Set
                Me.aDHeightField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ADWidth() As Integer
            Get
                Return Me.aDWidthField
            End Get
            Set
                Me.aDWidthField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsConnectionResponse
        
        Private actionToTakeField As Integer
        
        Private hostPublicIPField As String
        
        '''<remarks/>
        Public Property ActionToTake() As Integer
            Get
                Return Me.actionToTakeField
            End Get
            Set
                Me.actionToTakeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HostPublicIP() As String
            Get
                Return Me.hostPublicIPField
            End Get
            Set
                Me.hostPublicIPField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsHostIPInfo
        
        Private hostPublicIPField As String
        
        Private hostLocalIPField As String
        
        '''<remarks/>
        Public Property HostPublicIP() As String
            Get
                Return Me.hostPublicIPField
            End Get
            Set
                Me.hostPublicIPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HostLocalIP() As String
            Get
                Return Me.hostLocalIPField
            End Get
            Set
                Me.hostLocalIPField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsComputerConfigurationInfo
        
        Private computerHDSerialNumberField As String
        
        Private computerMacAddressField As String
        
        Private computerNameField As String
        
        '''<remarks/>
        Public Property ComputerHDSerialNumber() As String
            Get
                Return Me.computerHDSerialNumberField
            End Get
            Set
                Me.computerHDSerialNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ComputerMacAddress() As String
            Get
                Return Me.computerMacAddressField
            End Get
            Set
                Me.computerMacAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ComputerName() As String
            Get
                Return Me.computerNameField
            End Get
            Set
                Me.computerNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsConnectionRequest
        
        Private firstConnectionField As Boolean
        
        Private computerConfigurationInfoField As ClsComputerConfigurationInfo
        
        Private hostIPInfoField As ClsHostIPInfo
        
        '''<remarks/>
        Public Property FirstConnection() As Boolean
            Get
                Return Me.firstConnectionField
            End Get
            Set
                Me.firstConnectionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ComputerConfigurationInfo() As ClsComputerConfigurationInfo
            Get
                Return Me.computerConfigurationInfoField
            End Get
            Set
                Me.computerConfigurationInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HostIPInfo() As ClsHostIPInfo
            Get
                Return Me.hostIPInfoField
            End Get
            Set
                Me.hostIPInfoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub OpenConnectionCompletedEventHandler(ByVal sender As Object, ByVal e As OpenConnectionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OpenConnectionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ClsConnectionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ClsConnectionResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub CloseConnectionCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub KeepConnectionCompletedEventHandler(ByVal sender As Object, ByVal e As KeepConnectionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class KeepConnectionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ClsConnectionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ClsConnectionResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetAdvertisingCompletedEventHandler(ByVal sender As Object, ByVal e As GetAdvertisingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAdvertisingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ClsAdvertisingInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ClsAdvertisingInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub SetSystemConfigurationCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub AdDisplayCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub AdClickThruCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub SubscriberCountCompletedEventHandler(ByVal sender As Object, ByVal e As SubscriberCountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SubscriberCountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ConnectedSubscriberCountCompletedEventHandler(ByVal sender As Object, ByVal e As ConnectedSubscriberCountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConnectedSubscriberCountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub DisConnectedSubscriberCountCompletedEventHandler(ByVal sender As Object, ByVal e As DisConnectedSubscriberCountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DisConnectedSubscriberCountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub IsConnectedSubscriberCompletedEventHandler(ByVal sender As Object, ByVal e As IsConnectedSubscriberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsConnectedSubscriberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub AddSubsciberAccountCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub EditSubsciberAccountCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetSubscriberAccountCompletedEventHandler(ByVal sender As Object, ByVal e As GetSubscriberAccountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSubscriberAccountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ClsSubscriberAccountData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ClsSubscriberAccountData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub UninstallClientProgramCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ChangeSubscriberWebPasswordCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ChangeSubscriberComputerPasswordCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetSubscriberStolenReportCompletedEventHandler(ByVal sender As Object, ByVal e As GetSubscriberStolenReportCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSubscriberStolenReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ClsSubscriberStolenReportData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ClsSubscriberStolenReportData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub AddSubsciberStolenReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub EditSubsciberStolenReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
